
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox MainContainerBox;

	private global::Gtk.VBox OutputBox;

	private global::Gtk.Alignment alignment3;

	private global::Gtk.Label SecondaryOutput;

	private global::Gtk.Label MainOutput;

	private global::Gtk.VBox ControlsBox;

	private global::Gtk.HBox MemoryBox;

	private global::Gtk.Alignment alignment2;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label MCLabel;

	private global::Gtk.Label MSLabel;

	private global::Gtk.Label MRLabel;

	private global::Gtk.Alignment alignment1;

	private global::Gtk.HBox MainButtonsBox;

	private global::Gtk.VBox EraseButtonsBox;

	private global::Gtk.Button DelButton;

	private global::Gtk.Button CButton;

	private global::Gtk.Button CEButton;

	private global::Gtk.VBox NumbersBox;

	private global::Gtk.HBox NumbersFirstBox;

	private global::Gtk.Button SevenButton;

	private global::Gtk.Button EightButton;

	private global::Gtk.Button NineButton;

	private global::Gtk.HBox NumbersSecondBox;

	private global::Gtk.Button FourButton;

	private global::Gtk.Button FiveButton;

	private global::Gtk.Button SixButton;

	private global::Gtk.HBox NumbersThirdBox;

	private global::Gtk.Button OneButton;

	private global::Gtk.Button TwoButton;

	private global::Gtk.Button ThreeButton;

	private global::Gtk.HBox NumbersFourthBox;

	private global::Gtk.Button ChangeSignButton;

	private global::Gtk.Button ZeroButton;

	private global::Gtk.Button DotButton;

	private global::Gtk.HBox OperationsBox;

	private global::Gtk.VBox OperationsLeftBox;

	private global::Gtk.Button DivideButton;

	private global::Gtk.Button MultiplyButton;

	private global::Gtk.Button SubtractButton;

	private global::Gtk.Button AddButton;

	private global::Gtk.VBox OperationsRightBox;

	private global::Gtk.Button InverseButton;

	private global::Gtk.Button SquareRootButton;

	private global::Gtk.Button ResultButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Calculator");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.DefaultWidth = 345;
		this.DefaultHeight = 359;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainContainerBox = new global::Gtk.VBox();
		this.MainContainerBox.Name = "MainContainerBox";
		this.MainContainerBox.Spacing = 20;
		this.MainContainerBox.BorderWidth = ((uint)(10));
		// Container child MainContainerBox.Gtk.Box+BoxChild
		this.OutputBox = new global::Gtk.VBox();
		this.OutputBox.Name = "OutputBox";
		this.OutputBox.Spacing = 5;
		// Container child OutputBox.Gtk.Box+BoxChild
		this.alignment3 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment3.HeightRequest = 5;
		this.alignment3.Name = "alignment3";
		this.OutputBox.Add(this.alignment3);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.OutputBox[this.alignment3]));
		w1.Position = 0;
		// Container child OutputBox.Gtk.Box+BoxChild
		this.SecondaryOutput = new global::Gtk.Label();
		this.SecondaryOutput.Name = "SecondaryOutput";
		this.OutputBox.Add(this.SecondaryOutput);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.OutputBox[this.SecondaryOutput]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child OutputBox.Gtk.Box+BoxChild
		this.MainOutput = new global::Gtk.Label();
		this.MainOutput.Name = "MainOutput";
		this.MainOutput.LabelProp = global::Mono.Unix.Catalog.GetString("0");
		this.OutputBox.Add(this.MainOutput);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.OutputBox[this.MainOutput]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.MainContainerBox.Add(this.OutputBox);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.MainContainerBox[this.OutputBox]));
		w4.Position = 0;
		// Container child MainContainerBox.Gtk.Box+BoxChild
		this.ControlsBox = new global::Gtk.VBox();
		this.ControlsBox.Name = "ControlsBox";
		this.ControlsBox.Spacing = 6;
		// Container child ControlsBox.Gtk.Box+BoxChild
		this.MemoryBox = new global::Gtk.HBox();
		this.MemoryBox.Name = "MemoryBox";
		this.MemoryBox.Spacing = 6;
		// Container child MemoryBox.Gtk.Box+BoxChild
		this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment2.Name = "alignment2";
		this.MemoryBox.Add(this.alignment2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.MemoryBox[this.alignment2]));
		w5.Position = 0;
		// Container child MemoryBox.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.MCLabel = new global::Gtk.Label();
		this.MCLabel.Name = "MCLabel";
		this.MCLabel.LabelProp = global::Mono.Unix.Catalog.GetString("MC");
		this.hbox2.Add(this.MCLabel);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.MCLabel]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.MSLabel = new global::Gtk.Label();
		this.MSLabel.Name = "MSLabel";
		this.MSLabel.LabelProp = global::Mono.Unix.Catalog.GetString("MS");
		this.hbox2.Add(this.MSLabel);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.MSLabel]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.MRLabel = new global::Gtk.Label();
		this.MRLabel.Name = "MRLabel";
		this.MRLabel.LabelProp = global::Mono.Unix.Catalog.GetString("MR");
		this.hbox2.Add(this.MRLabel);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.MRLabel]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.MemoryBox.Add(this.hbox2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.MemoryBox[this.hbox2]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child MemoryBox.Gtk.Box+BoxChild
		this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		this.MemoryBox.Add(this.alignment1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.MemoryBox[this.alignment1]));
		w10.Position = 2;
		this.ControlsBox.Add(this.MemoryBox);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.ControlsBox[this.MemoryBox]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child ControlsBox.Gtk.Box+BoxChild
		this.MainButtonsBox = new global::Gtk.HBox();
		this.MainButtonsBox.Name = "MainButtonsBox";
		this.MainButtonsBox.Spacing = 6;
		// Container child MainButtonsBox.Gtk.Box+BoxChild
		this.EraseButtonsBox = new global::Gtk.VBox();
		this.EraseButtonsBox.Name = "EraseButtonsBox";
		this.EraseButtonsBox.Spacing = 5;
		// Container child EraseButtonsBox.Gtk.Box+BoxChild
		this.DelButton = new global::Gtk.Button();
		this.DelButton.WidthRequest = 50;
		this.DelButton.HeightRequest = 50;
		this.DelButton.CanFocus = true;
		this.DelButton.Name = "DelButton";
		this.DelButton.UseUnderline = true;
		this.DelButton.Label = global::Mono.Unix.Catalog.GetString("←");
		this.EraseButtonsBox.Add(this.DelButton);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.EraseButtonsBox[this.DelButton]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child EraseButtonsBox.Gtk.Box+BoxChild
		this.CButton = new global::Gtk.Button();
		this.CButton.WidthRequest = 50;
		this.CButton.HeightRequest = 50;
		this.CButton.CanFocus = true;
		this.CButton.Name = "CButton";
		this.CButton.UseUnderline = true;
		this.CButton.Label = global::Mono.Unix.Catalog.GetString("C");
		this.EraseButtonsBox.Add(this.CButton);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.EraseButtonsBox[this.CButton]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child EraseButtonsBox.Gtk.Box+BoxChild
		this.CEButton = new global::Gtk.Button();
		this.CEButton.WidthRequest = 50;
		this.CEButton.HeightRequest = 105;
		this.CEButton.CanFocus = true;
		this.CEButton.Name = "CEButton";
		this.CEButton.UseUnderline = true;
		this.CEButton.Label = global::Mono.Unix.Catalog.GetString("CE");
		this.EraseButtonsBox.Add(this.CEButton);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.EraseButtonsBox[this.CEButton]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		this.MainButtonsBox.Add(this.EraseButtonsBox);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.MainButtonsBox[this.EraseButtonsBox]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child MainButtonsBox.Gtk.Box+BoxChild
		this.NumbersBox = new global::Gtk.VBox();
		this.NumbersBox.Name = "NumbersBox";
		this.NumbersBox.Spacing = 5;
		// Container child NumbersBox.Gtk.Box+BoxChild
		this.NumbersFirstBox = new global::Gtk.HBox();
		this.NumbersFirstBox.Name = "NumbersFirstBox";
		this.NumbersFirstBox.Spacing = 5;
		// Container child NumbersFirstBox.Gtk.Box+BoxChild
		this.SevenButton = new global::Gtk.Button();
		this.SevenButton.WidthRequest = 50;
		this.SevenButton.HeightRequest = 50;
		this.SevenButton.CanFocus = true;
		this.SevenButton.Name = "SevenButton";
		this.SevenButton.UseUnderline = true;
		this.SevenButton.Label = global::Mono.Unix.Catalog.GetString("7");
		this.NumbersFirstBox.Add(this.SevenButton);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.NumbersFirstBox[this.SevenButton]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child NumbersFirstBox.Gtk.Box+BoxChild
		this.EightButton = new global::Gtk.Button();
		this.EightButton.WidthRequest = 50;
		this.EightButton.HeightRequest = 50;
		this.EightButton.CanFocus = true;
		this.EightButton.Name = "EightButton";
		this.EightButton.UseUnderline = true;
		this.EightButton.Label = global::Mono.Unix.Catalog.GetString("8");
		this.NumbersFirstBox.Add(this.EightButton);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.NumbersFirstBox[this.EightButton]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child NumbersFirstBox.Gtk.Box+BoxChild
		this.NineButton = new global::Gtk.Button();
		this.NineButton.WidthRequest = 50;
		this.NineButton.HeightRequest = 50;
		this.NineButton.CanFocus = true;
		this.NineButton.Name = "NineButton";
		this.NineButton.UseUnderline = true;
		this.NineButton.Label = global::Mono.Unix.Catalog.GetString("9");
		this.NumbersFirstBox.Add(this.NineButton);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.NumbersFirstBox[this.NineButton]));
		w18.Position = 2;
		w18.Expand = false;
		w18.Fill = false;
		this.NumbersBox.Add(this.NumbersFirstBox);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.NumbersBox[this.NumbersFirstBox]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child NumbersBox.Gtk.Box+BoxChild
		this.NumbersSecondBox = new global::Gtk.HBox();
		this.NumbersSecondBox.Name = "NumbersSecondBox";
		this.NumbersSecondBox.Spacing = 5;
		// Container child NumbersSecondBox.Gtk.Box+BoxChild
		this.FourButton = new global::Gtk.Button();
		this.FourButton.WidthRequest = 50;
		this.FourButton.HeightRequest = 50;
		this.FourButton.CanFocus = true;
		this.FourButton.Name = "FourButton";
		this.FourButton.UseUnderline = true;
		this.FourButton.Label = global::Mono.Unix.Catalog.GetString("4");
		this.NumbersSecondBox.Add(this.FourButton);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.NumbersSecondBox[this.FourButton]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child NumbersSecondBox.Gtk.Box+BoxChild
		this.FiveButton = new global::Gtk.Button();
		this.FiveButton.WidthRequest = 50;
		this.FiveButton.HeightRequest = 50;
		this.FiveButton.CanFocus = true;
		this.FiveButton.Name = "FiveButton";
		this.FiveButton.UseUnderline = true;
		this.FiveButton.Label = global::Mono.Unix.Catalog.GetString("5");
		this.NumbersSecondBox.Add(this.FiveButton);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.NumbersSecondBox[this.FiveButton]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child NumbersSecondBox.Gtk.Box+BoxChild
		this.SixButton = new global::Gtk.Button();
		this.SixButton.WidthRequest = 50;
		this.SixButton.HeightRequest = 50;
		this.SixButton.CanFocus = true;
		this.SixButton.Name = "SixButton";
		this.SixButton.UseUnderline = true;
		this.SixButton.Label = global::Mono.Unix.Catalog.GetString("6");
		this.NumbersSecondBox.Add(this.SixButton);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.NumbersSecondBox[this.SixButton]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		this.NumbersBox.Add(this.NumbersSecondBox);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.NumbersBox[this.NumbersSecondBox]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		// Container child NumbersBox.Gtk.Box+BoxChild
		this.NumbersThirdBox = new global::Gtk.HBox();
		this.NumbersThirdBox.Name = "NumbersThirdBox";
		this.NumbersThirdBox.Spacing = 5;
		// Container child NumbersThirdBox.Gtk.Box+BoxChild
		this.OneButton = new global::Gtk.Button();
		this.OneButton.WidthRequest = 50;
		this.OneButton.HeightRequest = 50;
		this.OneButton.CanFocus = true;
		this.OneButton.Name = "OneButton";
		this.OneButton.UseUnderline = true;
		this.OneButton.Label = global::Mono.Unix.Catalog.GetString("1");
		this.NumbersThirdBox.Add(this.OneButton);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.NumbersThirdBox[this.OneButton]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		// Container child NumbersThirdBox.Gtk.Box+BoxChild
		this.TwoButton = new global::Gtk.Button();
		this.TwoButton.WidthRequest = 50;
		this.TwoButton.HeightRequest = 50;
		this.TwoButton.CanFocus = true;
		this.TwoButton.Name = "TwoButton";
		this.TwoButton.UseUnderline = true;
		this.TwoButton.Label = global::Mono.Unix.Catalog.GetString("2");
		this.NumbersThirdBox.Add(this.TwoButton);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.NumbersThirdBox[this.TwoButton]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		// Container child NumbersThirdBox.Gtk.Box+BoxChild
		this.ThreeButton = new global::Gtk.Button();
		this.ThreeButton.WidthRequest = 50;
		this.ThreeButton.HeightRequest = 50;
		this.ThreeButton.CanFocus = true;
		this.ThreeButton.Name = "ThreeButton";
		this.ThreeButton.UseUnderline = true;
		this.ThreeButton.Label = global::Mono.Unix.Catalog.GetString("3");
		this.NumbersThirdBox.Add(this.ThreeButton);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.NumbersThirdBox[this.ThreeButton]));
		w26.Position = 2;
		w26.Expand = false;
		w26.Fill = false;
		this.NumbersBox.Add(this.NumbersThirdBox);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.NumbersBox[this.NumbersThirdBox]));
		w27.Position = 2;
		w27.Expand = false;
		w27.Fill = false;
		// Container child NumbersBox.Gtk.Box+BoxChild
		this.NumbersFourthBox = new global::Gtk.HBox();
		this.NumbersFourthBox.Name = "NumbersFourthBox";
		this.NumbersFourthBox.Spacing = 5;
		// Container child NumbersFourthBox.Gtk.Box+BoxChild
		this.ChangeSignButton = new global::Gtk.Button();
		this.ChangeSignButton.WidthRequest = 50;
		this.ChangeSignButton.HeightRequest = 50;
		this.ChangeSignButton.CanFocus = true;
		this.ChangeSignButton.Name = "ChangeSignButton";
		this.ChangeSignButton.UseUnderline = true;
		this.ChangeSignButton.Label = global::Mono.Unix.Catalog.GetString("±");
		this.NumbersFourthBox.Add(this.ChangeSignButton);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.NumbersFourthBox[this.ChangeSignButton]));
		w28.Position = 0;
		w28.Expand = false;
		w28.Fill = false;
		// Container child NumbersFourthBox.Gtk.Box+BoxChild
		this.ZeroButton = new global::Gtk.Button();
		this.ZeroButton.WidthRequest = 50;
		this.ZeroButton.HeightRequest = 50;
		this.ZeroButton.CanFocus = true;
		this.ZeroButton.Name = "ZeroButton";
		this.ZeroButton.UseUnderline = true;
		this.ZeroButton.Label = global::Mono.Unix.Catalog.GetString("0");
		this.NumbersFourthBox.Add(this.ZeroButton);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.NumbersFourthBox[this.ZeroButton]));
		w29.Position = 1;
		w29.Expand = false;
		w29.Fill = false;
		// Container child NumbersFourthBox.Gtk.Box+BoxChild
		this.DotButton = new global::Gtk.Button();
		this.DotButton.WidthRequest = 50;
		this.DotButton.HeightRequest = 50;
		this.DotButton.CanFocus = true;
		this.DotButton.Name = "DotButton";
		this.DotButton.UseUnderline = true;
		this.DotButton.Label = global::Mono.Unix.Catalog.GetString(".");
		this.NumbersFourthBox.Add(this.DotButton);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.NumbersFourthBox[this.DotButton]));
		w30.Position = 2;
		w30.Expand = false;
		w30.Fill = false;
		this.NumbersBox.Add(this.NumbersFourthBox);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.NumbersBox[this.NumbersFourthBox]));
		w31.PackType = ((global::Gtk.PackType)(1));
		w31.Position = 3;
		w31.Expand = false;
		w31.Fill = false;
		this.MainButtonsBox.Add(this.NumbersBox);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.MainButtonsBox[this.NumbersBox]));
		w32.Position = 1;
		w32.Expand = false;
		w32.Fill = false;
		// Container child MainButtonsBox.Gtk.Box+BoxChild
		this.OperationsBox = new global::Gtk.HBox();
		this.OperationsBox.Name = "OperationsBox";
		this.OperationsBox.Spacing = 5;
		// Container child OperationsBox.Gtk.Box+BoxChild
		this.OperationsLeftBox = new global::Gtk.VBox();
		this.OperationsLeftBox.Name = "OperationsLeftBox";
		this.OperationsLeftBox.Spacing = 5;
		// Container child OperationsLeftBox.Gtk.Box+BoxChild
		this.DivideButton = new global::Gtk.Button();
		this.DivideButton.WidthRequest = 50;
		this.DivideButton.HeightRequest = 50;
		this.DivideButton.CanFocus = true;
		this.DivideButton.Name = "DivideButton";
		this.DivideButton.UseUnderline = true;
		this.DivideButton.Label = global::Mono.Unix.Catalog.GetString("÷");
		this.OperationsLeftBox.Add(this.DivideButton);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.OperationsLeftBox[this.DivideButton]));
		w33.Position = 0;
		w33.Expand = false;
		w33.Fill = false;
		// Container child OperationsLeftBox.Gtk.Box+BoxChild
		this.MultiplyButton = new global::Gtk.Button();
		this.MultiplyButton.WidthRequest = 50;
		this.MultiplyButton.HeightRequest = 50;
		this.MultiplyButton.CanFocus = true;
		this.MultiplyButton.Name = "MultiplyButton";
		this.MultiplyButton.UseUnderline = true;
		this.MultiplyButton.Label = global::Mono.Unix.Catalog.GetString("×");
		this.OperationsLeftBox.Add(this.MultiplyButton);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.OperationsLeftBox[this.MultiplyButton]));
		w34.Position = 1;
		w34.Expand = false;
		w34.Fill = false;
		// Container child OperationsLeftBox.Gtk.Box+BoxChild
		this.SubtractButton = new global::Gtk.Button();
		this.SubtractButton.WidthRequest = 50;
		this.SubtractButton.HeightRequest = 50;
		this.SubtractButton.CanFocus = true;
		this.SubtractButton.Name = "SubtractButton";
		this.SubtractButton.UseUnderline = true;
		this.SubtractButton.Label = global::Mono.Unix.Catalog.GetString("-");
		this.OperationsLeftBox.Add(this.SubtractButton);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.OperationsLeftBox[this.SubtractButton]));
		w35.Position = 2;
		w35.Expand = false;
		w35.Fill = false;
		// Container child OperationsLeftBox.Gtk.Box+BoxChild
		this.AddButton = new global::Gtk.Button();
		this.AddButton.WidthRequest = 50;
		this.AddButton.HeightRequest = 50;
		this.AddButton.CanFocus = true;
		this.AddButton.Name = "AddButton";
		this.AddButton.UseUnderline = true;
		this.AddButton.Label = global::Mono.Unix.Catalog.GetString("+");
		this.OperationsLeftBox.Add(this.AddButton);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.OperationsLeftBox[this.AddButton]));
		w36.Position = 3;
		w36.Expand = false;
		w36.Fill = false;
		this.OperationsBox.Add(this.OperationsLeftBox);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.OperationsBox[this.OperationsLeftBox]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		// Container child OperationsBox.Gtk.Box+BoxChild
		this.OperationsRightBox = new global::Gtk.VBox();
		this.OperationsRightBox.Name = "OperationsRightBox";
		this.OperationsRightBox.Spacing = 5;
		// Container child OperationsRightBox.Gtk.Box+BoxChild
		this.InverseButton = new global::Gtk.Button();
		this.InverseButton.WidthRequest = 50;
		this.InverseButton.HeightRequest = 50;
		this.InverseButton.CanFocus = true;
		this.InverseButton.Name = "InverseButton";
		this.InverseButton.UseUnderline = true;
		this.InverseButton.Label = global::Mono.Unix.Catalog.GetString("1/x");
		this.OperationsRightBox.Add(this.InverseButton);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.OperationsRightBox[this.InverseButton]));
		w38.Position = 0;
		w38.Expand = false;
		w38.Fill = false;
		// Container child OperationsRightBox.Gtk.Box+BoxChild
		this.SquareRootButton = new global::Gtk.Button();
		this.SquareRootButton.WidthRequest = 50;
		this.SquareRootButton.HeightRequest = 50;
		this.SquareRootButton.CanFocus = true;
		this.SquareRootButton.Name = "SquareRootButton";
		this.SquareRootButton.UseUnderline = true;
		this.SquareRootButton.Label = global::Mono.Unix.Catalog.GetString("√");
		this.OperationsRightBox.Add(this.SquareRootButton);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.OperationsRightBox[this.SquareRootButton]));
		w39.Position = 1;
		w39.Expand = false;
		w39.Fill = false;
		// Container child OperationsRightBox.Gtk.Box+BoxChild
		this.ResultButton = new global::Gtk.Button();
		this.ResultButton.WidthRequest = 50;
		this.ResultButton.HeightRequest = 105;
		this.ResultButton.CanFocus = true;
		this.ResultButton.Name = "ResultButton";
		this.ResultButton.UseUnderline = true;
		this.ResultButton.Label = global::Mono.Unix.Catalog.GetString("=");
		this.OperationsRightBox.Add(this.ResultButton);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.OperationsRightBox[this.ResultButton]));
		w40.Position = 2;
		w40.Expand = false;
		w40.Fill = false;
		this.OperationsBox.Add(this.OperationsRightBox);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.OperationsBox[this.OperationsRightBox]));
		w41.Position = 1;
		w41.Expand = false;
		w41.Fill = false;
		this.MainButtonsBox.Add(this.OperationsBox);
		global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.MainButtonsBox[this.OperationsBox]));
		w42.Position = 2;
		w42.Expand = false;
		w42.Fill = false;
		this.ControlsBox.Add(this.MainButtonsBox);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.ControlsBox[this.MainButtonsBox]));
		w43.Position = 1;
		w43.Expand = false;
		w43.Fill = false;
		this.MainContainerBox.Add(this.ControlsBox);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.MainContainerBox[this.ControlsBox]));
		w44.Position = 1;
		w44.Expand = false;
		w44.Fill = false;
		this.Add(this.MainContainerBox);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
